name: notely
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+9
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  theme_provider: ^0.5.0
  fl_chart: ^0.55.0
  rename: ^2.0.1
  flutter_secure_storage: ^6.0.0
  page_transition: ^2.0.9
  day_night_switcher: ^0.2.0+1
  package_info_plus: ^1.4.2
  fl_toast: ^3.1.0
  dropdown_button2: ^1.6.2
  intl: ^0.17.0
  flutter_local_notifications: ^11.0.1
  flutter_acrylic: ^1.0.0
  date_picker_timeline: ^1.2.3
  flutter_platform_alert: ^0.3.0
  flutter_inappwebview: ^6.0.0-beta.22
  flutter_spinkit: ^5.1.0
  device_info_plus: ^4.1.2
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.3.0
  mailto: ^2.0.0
  url_launcher: ^6.1.10
dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/notely.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900