// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3g7zTHMtOuXu8qMhlaKTA53A0uExbQw',
    appId: '1:845125974911:android:a95995adb91b1a720bb84a',
    messagingSenderId: '845125974911',
    projectId: 'notely-ch',
    databaseURL: 'https://notely-ch-default-rtdb.firebaseio.com',
    storageBucket: 'notely-ch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-iUd3WEADCp1vXC4k0QxaJwAP5a52tM',
    appId: '1:845125974911:ios:76de159134daa3760bb84a',
    messagingSenderId: '845125974911',
    projectId: 'notely-ch',
    databaseURL: 'https://notely-ch-default-rtdb.firebaseio.com',
    storageBucket: 'notely-ch.appspot.com',
    iosBundleId: 'ch.thilojaeggi.notely',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHApPswAq058Jys9tR5uyd6uGbLi7rXcQ',
    appId: '1:845125974911:web:0299315e8748643a0bb84a',
    messagingSenderId: '845125974911',
    projectId: 'notely-ch',
    authDomain: 'notely-ch.firebaseapp.com',
    databaseURL: 'https://notely-ch-default-rtdb.firebaseio.com',
    storageBucket: 'notely-ch.appspot.com',
    measurementId: 'G-840SVX1MSY',
  );

}