name: Build Android aab

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.8.0
        with:
            flutter-version: '3.7.7'
            channel: 'stable'
          
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore
        
      - name: Get packages          
        run: flutter pub get
        
      - name: Build Android App Bundle      
        run: flutter build appbundle --release
        
      - name: Sign Android App Bundle
        run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/app-release.aab upload
      
      - name: Upload aab to GitHub        
        uses: actions/upload-artifact@v3
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/release/app-release-signed.aab
