name: Build Android aab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.7.1
        with:
          flutter-version: '3.3.3'
          
      - name: Create the Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch release.keystore.asc > $RUNNER_TEMP/app/upload.keystore
          
      - name: Output Direcotry ls
        run: ls $RUNNER_TEMP/
        
      - name: Get packages          
        run: flutter pub get
        
      - name: Build Android App Bundle      
        run: flutter build appbundle --release
        
      - name: Sign Android App Bundle
        run: jarsigner -keystore $RUNNER_TEMP/app/upload.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEYSTORE_PASSWORD_ALIAS }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/*.aab upload
      
      - name: Upload aab to GitHub        
        uses: actions/upload-artifact@v3
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/release/app-release-signed.aab
